# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: Coverity Check

on:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '.gitignore'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
  schedule:
    - cron: '12 9 * * 3'

jobs:
  test:
    uses: xmidt-org/.github/.github/workflows/meson-coverity.yml@main
    with:
      repo: $GITHUB_REPOSITORY
      sha: $GITHUB_SHA
    secrets:
      coverity_key: ${{ secrets.COVERITY_KEY }}
