# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    paths:
      - "CHANGELOG.md" # only try to tag if the CHANGELOG has been updated.
    branches:
      - main

jobs:
  release:
    uses: xmidt-org/.github/.github/workflows/meson-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
